liip_monitor_health_interface:
    path: /
    defaults:  { _controller:  liip_monitor.health.controller:indexAction, _method: GET }

liip_monitor_list_checks:
    path: /checks
    defaults:  { _controller:  liip_monitor.health.controller:listAction }

liip_monitor_run_all_checks:
    path:   /run
    defaults:  { _controller:  liip_monitor.health.controller:runAllChecksAction }

liip_monitor_run_single_check:
    path:   /run/{checkId}
    defaults:  { _controller:  liip_monitor.health.controller:runSingleCheckAction }

liip_monitor_list_groups:
    path:   /groups
    defaults:  { _controller:  liip_monitor.health.controller:listGroups }    
        
liip_monitor_run_group_check:
    path:   /rungroups
    defaults:  { _controller:  liip_monitor.health.controller:runAllGroupChecksAction }
